name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Let's cook pasta and feed monsters!"
        pr-message: "Let's cook pasta and feed monsters!"

    - name: Reverse secret
      run: |
        echo "REVERSE_SECRET=${{ secrets.CTF_FLAG }}" >> $GITHUB_ENV
        echo "REVERSE_SECRET=${REVERSE_SECRET}"
